// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Canonical fallback for kppdf-postgres local-dev container (matches .env.example).
    // Production envs MUST set DATABASE_URL explicitly (no fallback used).
    url: process.env.DATABASE_URL || "postgresql://kppdf:kppdf123@localhost:5432/kppdf?sslmode=disable",
  },
});
