#!/usr/bin/env bash
set +e

echo '=== 1. Check .gitignore for tsbuildinfo + next-env.d.ts ==='
grep -E 'tsbuildinfo|next-env|\.tsbuildinfo' .gitignore 2>&1 || echo 'no matches in .gitignore'

echo
echo '=== 2. Discard tsconfig.tsbuildinfo (regenerated build cache) ==='
git checkout -- tsconfig.tsbuildinfo 2>&1
echo 'discarded'
git status --short tsconfig.tsbuildinfo 2>&1 || echo 'gone'

echo
echo '=== 3. Add tsbuildinfo + next-env.d.ts to .gitignore (hygiene) ==='
# Check if already in .gitignore
if ! grep -qE 'tsbuildinfo|next-env\.d\.ts' .gitignore; then
  # Append (be careful with existing content)
  echo '' >> .gitignore
  echo '# TypeScript build cache (regenerated by tsc on every build)' >> .gitignore
  echo 'tsconfig.tsbuildinfo' >> .gitignore
  echo '' >> .gitignore
  echo '# Next.js auto-generated' >> .gitignore
  echo 'next-env.d.ts' >> .gitignore
  echo 'appended to .gitignore'
else
  echo 'already in .gitignore'
fi

echo
echo '=== 4. Untrack tsconfig.tsbuildinfo + next-env.d.ts (git rm --cached) ==='
git rm --cached tsconfig.tsbuildinfo 2>&1 || echo 'not tracked'
git rm --cached next-env.d.ts 2>&1 || echo 'not tracked'

echo
echo '=== 5. Stage .gitignore update ==='
git add .gitignore 2>&1
git status --short 2>&1 | head -10

echo
echo '=== 6. Commit the .gitignore update ==='
mkdir -p .tmp
cat > .tmp/commit-msg-2.txt << 'MSGEOF'
chore(gitignore): untrack tsconfig.tsbuildinfo + next-env.d.ts

Both files are auto-regenerated by tsc / next dev on every build and were
causing rebase friction (unstaged modifications blocking git pull --rebase).
Untracking them keeps the working tree clean for future rebase operations.

- tsconfig.tsbuildinfo: tsc incremental build cache
- next-env.d.ts: next.js auto-generated types
MSGEOF
git commit -F .tmp/commit-msg-2.txt 2>&1 | tail -5

echo
echo '=== 7. Now rebase against origin/main ==='
git pull --rebase origin main 2>&1
PULL_EXIT=$?
echo "pull exit: $PULL_EXIT"

echo
echo '=== 8. Status after rebase ==='
git status 2>&1 | head -20

echo
echo '=== 9. Conflict files? ==='
CONFLICTS=$(git diff --name-only --diff-filter=U 2>&1)
if [ -n "$CONFLICTS" ]; then
  echo "CONFLICTS: $CONFLICTS"
  for f in $CONFLICTS; do
    echo "  $f: resolving with --theirs (prefer remote/architect outputs)"
    git checkout --theirs "$f" 2>&1
    git add "$f" 2>&1
  done
  GIT_EDITOR=true git rebase --continue 2>&1
else
  echo 'NO_CONFLICTS'
fi

echo
echo '=== 10. Final log ==='
git log --oneline -n 6 2>&1

echo
echo '=== 11. Final tracking ==='
git status -sb 2>&1 | head -3

echo
echo '=== 12. Push to origin/main ==='
git push origin main 2>&1
PUSH_EXIT=$?
echo "push exit: $PUSH_EXIT"

echo
echo '=== 13. Final state after push ==='
git status -sb 2>&1 | head -3
git log --oneline -n 4 2>&1
